### PR TITLE
fixed bottom trace between vias not showing and added a test.

### LINKED ISSUE #24: Bottom traces are not drawn
Reproduction:

```tsx
export const BlinkingLED = () => (
  <board width="40mm" height="30mm">
    <chip footprint="dip8" name="U1" pcbX="-15mm" pcbY="0mm" pinLabels={{
      1: "GND",
      2: "TRIG",
      3: "OUT", 
      4: "RST",
      5: "CTRL",
      6: "THRES",
      7: "DSCHG",
      8: "VCC"
    }} />
    
    <led name="LED1" pcbX="10mm" pcbY="5mm" />
    
    <resistor name="R1" resistance="330" footprint="0805" pcbX="0mm" pcbY="-5mm" />
    <resistor name="R2" resistance="10k" footprint="0805" pcbX="5mm" pcbY="-5mm" />
    <capacitor name="C1" capacitance="100nF" footprint="0805" pcbX="10mm" pcbY="-5mm" />
    
    <trace from=".U1 .GND" to=".R1 .pin1" />
    <trace from=".R1 .pin2" to=".LED1 .pin1" />
    <trace from=".LED1 .pin2" to=".U1 .OUT" />
    <trace from=".U1 .DSCHG" to=".U1 .CTRL" />
    <trace from=".U1 .THRES" to=".R2 .pin1" />
    <trace from=".R2 .pin2" to=".C1 .pin1" />
    <trace from=".C1 .pin2" to="net.VCC" /> 
    <trace from=".U1 .VCC" to="net.VCC" />
    <trace from=".U1 .RST" to="net.VCC" />
  </board>
)
```

Image

Image

### PR DESCRIPTION
**Pull request by Abse2001**
/closes #24 

https://github.com/user-attachments/assets/e3da558d-2223-4525-a9e8-66cded635bca

### CODE REVIEW

**Comment by Abse2001** [comment]
Before
image
After
image

File: src/soup-to-3d/index.ts [hunk 1]
```diff
@@ -130,35 +130,47 @@ export const createBoardGeomFromSoup = (soup: AnySoupElement[]): Geom3[] => {
...
+
       const linePath = line(route.map((p) => [p.x, p.y]))
+      const layerSign =
+        route[0]!.route_type === "via"
+          ? route[0]!.to_layer === "top"
+            ? 1
+            : -1
+          : route[0]!.layer === "top"
+            ? 1
+            : -1
```
Comment (seveibar) [inline src/soup-to-3d/index.ts:172]: so this is good, but technically there are also "inner traces" that don't fall on the top or bottom layer, there may be a more future-proof way to do this

**Review by seveibar — APPROVED** [review]

File: src/soup-to-3d/index.ts (hunk 1 above)
Comment (Abse2001) [reply src/soup-to-3d/index.ts:172]: I will try to repro inner traces later and handle them.
